backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Produits"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Vidéo", name: "video", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
